(
    MAIN_MENU,
    # Flujo de Venta
    ADD_SALE_CHOOSE_CATEGORY, ADD_SALE_CHOOSE_PRODUCT,
    ADD_SALE_CHOOSE_OPTION_1, ADD_SALE_CHOOSE_OPTION_2,
    ADD_SALE_INPUT_QUANTITY, ADD_SALE_INPUT_CLIENT,
    # Flujo de Gasto
    ADD_EXPENSE_CHOOSE_CATEGORY, ADD_EXPENSE_CHOOSE_SUBCATEGORY,
    ADD_EXPENSE_INPUT_DESCRIPTION, ADD_EXPENSE_INPUT_AMOUNT,
    # Flujos especiales de Gasto
    ADD_EXPENSE_CANJE_GET_ENTITY, ADD_EXPENSE_CANJE_GET_ITEM,
    ADD_EXPENSE_CANJE_GET_QUANTITY,
    ADD_EXPENSE_PROVEEDORES_GET_NAME, ADD_EXPENSE_PROVEEDORES_GET_ITEM,
    ADD_EXPENSE_PROVEEDORES_GET_QUANTITY,
    # Flujo de Balance
    QUERY_BALANCE_CHOOSE_YEAR, QUERY_BALANCE_CHOOSE_MONTH,
    # Flujo de Deudas
    DEBT_MENU,
    CREATE_DEBT_GET_NAME, CREATE_DEBT_GET_AMOUNT,
    PAY_DEBT_CHOOSE_DEBT, PAY_DEBT_GET_AMOUNT,
    MODIFY_DEBT_CHOOSE_DEBT, MODIFY_DEBT_GET_AMOUNT,
    # Flujo Mayorista
    ADD_WHOLESALE_MENU,
    ADD_WHOLESALE_GET_NAME, ADD_WHOLESALE_GET_PRODUCT,
    ADD_WHOLESALE_GET_QUANTITY, ADD_WHOLESALE_GET_PAID_AMOUNT,
    ADD_WHOLESALE_GET_TOTAL_AMOUNT,
    # Flujo de Cheques (Simplificado)
    CHECKS_MENU,
    CHECKS_GET_ENTITY,
    CHECKS_GET_INITIAL_AMOUNT,
    CHECKS_GET_COMMISSION,
    CHECKS_GET_DUE_DATE,
    # Flujo de Pagos Futuros (Simplificado)
    FUTURE_PAYMENTS_MENU,
    FUTURE_PAYMENTS_GET_ENTITY,
    FUTURE_PAYMENTS_GET_INITIAL_AMOUNT,
    FUTURE_PAYMENTS_GET_COMMISSION,
    FUTURE_PAYMENTS_GET_DUE_DATE,
    # Flujo simplificado para modificar pago
    MODIFY_PAYMENT_CHOOSE_SENA,
    MODIFY_PAYMENT_GET_AMOUNT
) = range(44)

# Nuevos estados añadidos al flujo de Pagos Futuros (se agregan al final para no alterar los anteriores)
FUTURE_PAYMENTS_GET_PRODUCT, FUTURE_PAYMENTS_GET_QUANTITY = range(44, 46)

# Persistent Menu Buttons
BTN_NEW_SALE = "💰 Registrar Venta"
BTN_NEW_WHOLESALE = "📦 Registrar Mayorista"
BTN_NEW_EXPENSE = "💸 Registrar Gasto"
BTN_DEBTS = "💳 Deudas"
BTN_BALANCE = "📈 Consultar Balance"
